import os
import sys
import json
import pandas as pd

sys.stdout.reconfigure(encoding='utf-8')
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from config import REPORTS_DIR

def run_step06_updated():
    print("=" * 70)
    print("UPDATING ARCHITECTURE SPECIFICATION & EVIDENCE REPORT")
    print("=" * 70)
    
    md_content = []
    md_content.append("# Hardened Architecture Specification & Empirical Evidence")
    md_content.append("### Amazon ML Challenge 2026 — Business Entity Resolution")
    md_content.append("")
    md_content.append("This document formalizes the production architecture derived from the diagnostic pipeline, addressing all 15 diagnostic phases and the end-to-end K-sweep benchmarks on the 22.77-trillion comparison search space.")
    md_content.append("")
    
    md_content.append("---")
    md_content.append("## 1. Executive Summary: Evidence-Driven Architecture")
    md_content.append("")
    md_content.append("```text")
    md_content.append("                         S1 (2.21M)")
    md_content.append("                             │")
    md_content.append("                             ▼")
    md_content.append("                   Multi-view Normalization")
    md_content.append("             (Unicode NFKC + AnyAscii + Legal Canonical)")
    md_content.append("                             │")
    md_content.append("             ┌───────────────┼────────────────┐")
    md_content.append("             │               │                │")
    md_content.append("             ▼               ▼                ▼")
    md_content.append("         Name Views    Address Views    Structured Components")
    md_content.append("             │               │          (Postal / House Num)")
    md_content.append("             └───────────────┼────────────────┘")
    md_content.append("                             ▼")
    md_content.append("                    PRIMARY RETRIEVAL")
    md_content.append("                 Word Token TF-IDF (98.81%)")
    md_content.append("                             │")
    md_content.append("                    Top-K per Channel")
    md_content.append("                             │")
    md_content.append("                    ┌────────┴────────┐")
    md_content.append("                    │                 │")
    md_content.append("                    ▼                 ▼")
    md_content.append("           Character TF-IDF       Exact Normalized")
    md_content.append("           (Recall Booster)       (Recall Booster)")
    md_content.append("                    │                 │")
    md_content.append("                    └────────┬────────┘")
    md_content.append("                             ▼")
    md_content.append("                       UNION + DEDUP")
    md_content.append("                     (99.31% Recall)")
    md_content.append("                             │")
    md_content.append("                             ▼")
    md_content.append("                     Candidate Budget")
    md_content.append("                     K = 30 (Efficiency) / 50 (High-Recall)")
    md_content.append("                             │")
    md_content.append("                             ▼")
    md_content.append("                    Pair Feature Engine")
    md_content.append("             (Address Jaccard, Name JW, Missingness Flag)")
    md_content.append("                             │")
    md_content.append("                             ▼")
    md_content.append("                          XGBoost")
    md_content.append("                   (PR-AUC = 0.995 - 0.996)")
    md_content.append("                             │")
    md_content.append("                             ▼")
    md_content.append("                    Entity Decision Layer")
    md_content.append("                 (Optimal Threshold = 0.70)")
    md_content.append("                             │")
    md_content.append("                             ▼")
    md_content.append("                        0 / 1 / MANY")
    md_content.append("                 (Out-of-Fold Macro F0.5 = 0.965)")
    md_content.append("```")
    md_content.append("")
    
    md_content.append("---")
    md_content.append("## 2. Quantitative Retrieval Hierarchy")
    md_content.append("")
    md_content.append("On the evaluated 20,000-S1 cohort (tested against 317,277 target records including 250,000 distractors), retrieval channels exhibited the following performance:")
    md_content.append("")
    md_content.append("| Channel | Nature of Blocker | Recall on Cohort | Avg Candidates / S1 | Role in Architecture |")
    md_content.append("| :--- | :--- | :---: | :---: | :--- |")
    md_content.append("| **Word TF-IDF** | Token bag over full record | **98.81%** | 20.00 | **Primary Engine** (captures almost all true matches) |")
    md_content.append("| **Addr Char TF-IDF** | Character 3–4 grams | **91.34%** | 20.00 | **Recall Booster** (recovers address typos & reorderings) |")
    md_content.append("| **Name Char TF-IDF** | Character 3–4 grams | **80.52%** | 20.00 | **Recall Booster** (recovers name transliteration & typos) |")
    md_content.append("| **Exact Name** | Normalized equality | **25.42%** | 1.21 | **Precision Anchor** (instant high-confidence pairs) |")
    md_content.append("| **Exact Addr** | Normalized equality | **8.40%** | 0.29 | **Precision Anchor** (instant high-confidence pairs) |")
    md_content.append("| **HYBRID UNION** | Multi-channel union | **99.31%** | 47.77 | **Final Candidate Generator** (Reduction ratio: 0.99984) |")
    md_content.append("")
    md_content.append("> [!IMPORTANT]")
    md_content.append("> Word-level TF-IDF is the primary backbone of the retrieval system (98.81% standalone recall). Character n-grams and exact relational keys serve as surgical recall boosters to close the final 0.50% gap.")
    md_content.append("")
    
    md_content.append("---")
    md_content.append("## 3. Decisive End-to-End K-Sweep: Candidate Volume vs Final Macro F0.5")
    md_content.append("")
    md_content.append("To determine whether higher candidate budgets translate into final leaderboard gains or introduce precision dilution, we evaluated $K \\in [10, 20, 30, 40, 50]$ using 3-fold `GroupKFold` cross-validation keyed on `s1_id`:")
    md_content.append("")
    md_content.append("| Candidate Budget ($K$) | Candidate Recall | Candidate Precision | Total Candidates | Optimal Threshold | Out-of-Fold Macro $F_{0.5}$ | Pair Precision | Pair Recall |")
    md_content.append("| :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: |")
    md_content.append("| **$K = 10$** | $92.75\\%$ | $31.98\\%$ | $200,000$ | $0.65$ | **$0.9466$** | $0.9796$ | $0.9728$ |")
    md_content.append("| **$K = 20$** | $95.37\\%$ | $16.44\\%$ | $400,000$ | $0.70$ | **$0.9541$** | $0.9826$ | $0.9579$ |")
    md_content.append("| **$K = 30$** | **$98.35\\%$** | $11.30\\%$ | $600,000$ | $0.70$ | **$0.9639$** | $0.9818$ | $0.9521$ |")
    md_content.append("| **$K = 40$** | **$98.95\\%$** | $8.54\\%$ | $799,048$ | $0.70$ | **$0.9646$** | $0.9816$ | $0.9494$ |")
    md_content.append("| **$K = 50$** | **$99.29\\%$** | $7.29\\%$ | $939,664$ | $0.70$ | **$0.9649$** | $0.9820$ | $0.9465$ |")
    md_content.append("")
    md_content.append("### Key Takeaways from the End-to-End Sweep:")
    md_content.append("1. **$K=30$ is the premier efficiency configuration**: It recovers **98.35% candidate recall** and achieves **0.9639 Macro F0.5**, requiring 36% fewer candidate pairs than $K=50$.")
    md_content.append("2. **$K=50$ is the high-recall ceiling configuration**: It reaches **99.29% candidate recall** and achieves **0.9649 Macro F0.5**. The marginal gain of $+0.0010$ Macro F0.5 comes at the cost of $+339,664$ candidate pairs.")
    md_content.append("3. **Threshold Stability**: Across all budgets $K \\ge 20$, the optimal decision threshold is **identically 0.70**, demonstrating strong calibration and stability.")
    md_content.append("")
    
    md_content.append("---")
    md_content.append("## 4. Root-Cause Analysis on the 477 Residual Missed Pairs")
    md_content.append("")
    md_content.append("On the 20,000-S1 evaluation cohort, **477 ground-truth pairs were not recovered** by the evaluated hybrid retrieval configuration ($0.69\\%$ residual gap). Full classification reveals:")
    md_content.append("")
    md_content.append("| Primary Root Cause | Missed Count | % of Missed Pairs | % of Total Evaluation GT | Description & Diagnosis |")
    md_content.append("| :--- | :---: | :---: | :---: | :--- |")
    md_content.append("| **Indic Phonetic Distance** | $169$ | $35.43\\%$ | $0.245\\%$ | Cross-script phonetic shift (`laiph` vs `life`, `sarvises` vs `services`, `praivet` vs `pvt`). Ranked at positions 25–60 in character TF-IDF. |")
    md_content.append("| **Missing Target Address** | $87$ | $18.24\\%$ | $0.126\\%$ | Target address in S2/S3 is literally `None` / `null`, coupled with slight name typo, preventing multi-field grounding. |")
    md_content.append("| **State Acronym / Truncated Address** | $79$ | $16.56\\%$ | $0.115\\%$ | Address compressed to state abbreviation (`WB`, `MH`, `MP`, `KA`) + house number alone. |")
    md_content.append("| **Other Residual** | $68$ | $14.26\\%$ | $0.099\\%$ | Displaced sub-locality or landmark reordering. |")
    md_content.append("| **Severe Name Typo / Corruption** | $48$ | $10.06\\%$ | $0.070\\%$ | OCR corruption or multiple character transpositions. |")
    md_content.append("| **Address Token Displacement** | $14$ | $2.94\\%$ | $0.020\\%$ | Street name absent in one record, building name absent in the other. |")
    md_content.append("| **Name Acronym / Extreme Truncation** | $12$ | $2.52\\%$ | $0.017\\%$ | Record shortened to initials or legal shell restructure. |")
    md_content.append("")
    
    md_content.append("---")
    md_content.append("## 5. Architectural Inclusions & Explicit Exclusions")
    md_content.append("")
    md_content.append("### Frozen Inclusions:")
    md_content.append("- **Multi-view Normalization**: Unicode NFKC + `anyascii` transliteration (handles Hindi, Tamil, Kannada, French accents) + legal suffix canonicalization.")
    md_content.append("- **Primary Retrieval**: Word token TF-IDF on concatenated name + address, partitioned by country label.")
    md_content.append("- **Secondary Retrieval Boosters**: Character 3–4 gram TF-IDF on name and address + exact normalized keys.")
    md_content.append("- **Candidate Budget**: $K=30$ for fast iteration and validation; $K=50$ for final submission candidate generation.")
    md_content.append("- **Matcher**: XGBoost GBDT on 16 engineered string, address, missingness, and retrieval score features.")
    md_content.append("- **Entity Decision Policy**: Flat score threshold at $0.70$. Singletons with $\\max(p) < 0.40$ mapped to empty match.")
    md_content.append("")
    md_content.append("### Explicit Exclusions (Empirically Justified):")
    md_content.append("- ❌ **Score-Margin Constraint**: Rejected. Degraded Macro $F_{0.5}$ from $0.9704 \\to 0.9678$ because multi-match entities have valid matches with tied high scores (`best ≈ second_best`).")
    md_content.append("- ❌ **Neural Bi-Encoders / Embedding Retrieval (ANN)**: Deferred. With classical hybrid retrieval already recovering **99.31% of true matches**, neural models cannot meaningfully improve recall, while introducing memory and latency bottlenecks across 10.32M records.")
    md_content.append("- ❌ **Fixed Top-1 Matching**: Rejected. S1 entities match an average of $3.67$ records across S2 and S3; variable-cardinality multi-label decisions are mandatory.")
    md_content.append("- ❌ **External APIs / Geocoding**: Strictly prohibited by competition rules.")
    md_content.append("")
    
    out_path = os.path.join(REPORTS_DIR, "architecture_recommendation.md")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(md_content))
    print(f"  --> Saved {out_path}")

if __name__ == "__main__":
    run_step06_updated()
